name: hotel_assistant
description: "Hotel Assistant"
publish_to: 'none'

version: 1.0.0+3
environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^8.0.2
  cupertino_icons: ^1.0.8


  # Firebase
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1
  firebase_messaging: ^16.1.2
  firebase_storage: ^13.0.2

  # Local notifications
  flutter_local_notifications: ^17.2.4

  # Photos
  image_picker: ^1.2.0
  photo_view: ^0.15.0

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: 'assets/hotel_assistant_bed_icon.png'


