org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -Dfile.encoding=UTF-8

android.useAndroidX=true
android.enableJetifier=true

org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
kotlin.incremental=false

android.newDsl=false
android.builtInKotlin=false